name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: '${{ secrets.FIRMWARE80_BUILD }}'

      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v4
        with:
          node-version-file: scripts/.nvmrc

      - name: Install node dependencies in scripts folder
        run: |
          cd scripts
          npm install

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: .
          toolchains: arm-zephyr-eabi
          manifest-file-name: west.yml
