name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          path: app
          submodules: recursive
          token: '${{ secrets.FIRMWARE80_BUILD }}'

      - name: Install west
        run: pip3 install --user -U west

#      - name: Use Node.js (.nvmrc)
#        uses: actions/setup-node@v4
#        with:
#          node-version-file: app/scripts/.nvmrc
#
#      - name: Install node dependencies in scripts folder
#        run: |
#          cd app/scripts
#          npm install

#      - name: Setup Zephyr project
#        uses: zephyrproject-rtos/action-zephyr-setup@v1
#        with:
#          app-path: app
#          toolchains: all
#
#      - name: workdir dir
#        run: pwd
#        if: always()
#
#      - name: list dir
#        run: tree -L 3 ..
#        if: always()
