name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@v4
        with:
          path: firmware-uhk80
          submodules: recursive
          token: '${{ secrets.FIRMWARE80_BUILD }}'

      - name: Install build dependencies
        run: sudo apt-get install -y gcc-arm-none-eabi

      - name: Install west
        run: pip3 install --user -U west

      - name: Install python dependencies of scripts
        run: |
          cd firmware-uhk80/scripts
          pip install -r requirements.txt

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: firmware-uhk80
          toolchains: arm-zephyr-eabi
          sdk-version: 0.16.8

#      - name: West init
#        run: west init -l .
#
#      - name: West update
#        run: west update

      - name: Git user setup
        run: |
          git config --global user.email "git-patch@uhk.com"
          git config --global user.name "Git Patch"

      - name: West patch
        run: west patch

      - name: West config
        run: west config --local build.cmake-args -- "-Wno-dev"
#
#      - name: West Zephyr export
#        run: west zephyr-export
#
      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v4
        with:
          node-version-file: firmware-uhk80/scripts/.nvmrc

      - name: Install node dependencies in scripts folder
        run: |
          cd firmware-uhk80/scripts
          npm install

      - name: Create firmware tarball
        run: |
          cd firmware-uhk80
          scripts/make-release.mjs --allowSha

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: firmware-uhk80/scripts/uhk-firmware-*.tar.gz
          compression-level: 0
          retention-days: 10
