name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: '${{ secrets.FIRMWARE80_BUILD }}'

      - name: Install build dependencies
        run: sudo apt-get install -y ninja-build ccache libc6-dev-i386 gcc-arm-none-eabi

      - name: Install west
        run: pip3 install --user -U west

      - name: Install python dependencies of scripts
        run: |
          cd scripts
          pip install -r requirements.txt

      - name: West init
        run: west init -l .

      - name: West update
        run: west update

      - name: West patch
        run: west patch

      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v4
        with:
          node-version-file: scripts/.nvmrc

      - name: Install node dependencies in scripts folder
        run: |
          cd scripts
          npm install

      - name: Create firmware tarball
        run: scripts/make-release.mjs --allowSha

      - name: List scripts folder
        run: ls -la scripts
